gormlog: true
ginmode: "release"

autotls: false
domain: ""
email: ""

mailgundomail: ""
mailgunkey: ""

mysql:
  username: "root"
  password: "rootroot"
  addr: "0.0.0.0"
  name: "aaimg2ascii"

log:
  path: ""
  filename: ""

commodityprice1: 1200
commodityprice2: 1000
commodityprice3: 800
freight: 60

